name: Test Get Previous Version Action

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - '.github/actions/get-previous-version/**'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        LATEST_125_VERSION: '1.25.34' # Update this when the latest 1.25.x version is released
    steps:
      - uses: actions/checkout@v3

      - name: Test patch version jump
        uses: ./.github/actions/get-previous-version
        id: test-patch
        with:
          weaviate_version: '1.25.34'
          jump_type: 'patch'
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify patch output
        run: |
          if [ "${{ steps.test-patch.outputs.previous_version }}" != "1.25.33" ]; then
            echo "Expected version 1.25.33, got ${{ steps.test-patch.outputs.previous_version }}"
            exit 1
          fi

      - name: Test multiple patch version jumps
        uses: ./.github/actions/get-previous-version
        id: test-patch-multiple
        with:
          weaviate_version: '1.25.34'
          jump_type: 'patch'
          jumps: '3'
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify patch output
        run: |
          if [ "${{ steps.test-patch-multiple.outputs.previous_version }}" != "1.25.31" ]; then
            echo "Expected version 1.25.31, got ${{ steps.test-patch-multiple.outputs.previous_version }}"
            exit 1
          fi

      - name: Test minor version jump
        uses: ./.github/actions/get-previous-version
        id: test-minor
        with:
          weaviate_version: '1.26.13'
          jump_type: 'minor'
          jumps: '1'
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify minor output
        run: |
          if [ "${{ steps.test-minor.outputs.previous_version }}" != "$LATEST_125_VERSION" ]; then
            echo "Expected version $LATEST_125_VERSION, got ${{ steps.test-minor.outputs.previous_version }}"
            exit 1
          fi

      - name: Test multiple minor jumps
        uses: ./.github/actions/get-previous-version
        id: test-multiple
        with:
          weaviate_version: '1.27.10'
          jump_type: 'minor'
          jumps: '2'
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify multiple jumps output
        run: |
          if [ "${{ steps.test-multiple.outputs.previous_version }}" != "$LATEST_125_VERSION" ]; then
            echo "Expected version $LATEST_125_VERSION, got ${{ steps.test-multiple.outputs.previous_version }}"
            exit 1
          fi

      - name: Test with invalid version
        uses: ./.github/actions/get-previous-version
        id: test-invalid
        continue-on-error: true
        with:
          weaviate_version: '0.0.0'
          jump_type: 'patch'
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify invalid version fails
        run: |
          if [ "${{ steps.test-invalid.outcome }}" != "failure" ]; then
            echo "Expected action to fail with invalid version"
            exit 1
          fi 
