name: Test Weaviate Version in Image Action

on:
    push:

jobs:
    basic-image:
        runs-on: ubuntu-latest
        env:
          IMAGE_TAG: "1.27.0"
          EXPECTED: "1.27.0"
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
          - name: Test weaviate-version-in-image action
            id: weaviate-version-in-image
            uses: ./.github/actions/weaviate-version-in-image
            with:
              image_tag: ${{ env.IMAGE_TAG }}
          - name: Verify that the retrieved version matches the expected one
            run: |
              echo "Expected: ${{ env.EXPECTED }}"
              echo "Actual: ${{ steps.weaviate-version-in-image.outputs.weaviate_version }}"
              if [ "${{ env.EXPECTED }}" != "${{ steps.weaviate-version-in-image.outputs.weaviate_version }}" ]; then
                echo "The retrieved version does not match the expected one."
                exit 1
              fi
    stable-image:
      runs-on: ubuntu-latest
      env:
        IMAGE_TAG: "stable-v1.25-b3bc753"
        EXPECTED: "1.25.21"
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Test weaviate-version-in-image action
          id: weaviate-version-in-image
          uses: ./.github/actions/weaviate-version-in-image
          with:
            image_tag: ${{ env.IMAGE_TAG }}
        - name: Verify that the retrieved version matches the expected one
          run: |
            echo "Expected: ${{ env.EXPECTED }}"
            echo "Actual: ${{ steps.weaviate-version-in-image.outputs.weaviate_version }}"
            if [ "${{ env.EXPECTED }}" != "${{ steps.weaviate-version-in-image.outputs.weaviate_version }}" ]; then
            echo "The retrieved version does not match the expected one."
            exit 1
            fi
    main-image:
      runs-on: ubuntu-latest
      env:
        IMAGE_TAG: "main-f759849"
        EXPECTED: "1.27.0-rc.0"
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Test weaviate-version-in-image action
          id: weaviate-version-in-image
          uses: ./.github/actions/weaviate-version-in-image
          with:
            image_tag: ${{ env.IMAGE_TAG }}
        - name: Verify that the retrieved version matches the expected one
          run: |
            echo "Expected: ${{ env.EXPECTED }}"
            echo "Actual: ${{ steps.weaviate-version-in-image.outputs.weaviate_version }}"
            if [ "${{ env.EXPECTED }}" != "${{ steps.weaviate-version-in-image.outputs.weaviate_version }}" ]; then
            echo "The retrieved version does not match the expected one."
            exit 1
            fi
    preview-image:
        runs-on: ubuntu-latest
        env:
          IMAGE_TAG: "preview--hnsw-pq-bq-prefill-compressed-vector-cache-in-parallel-d351d51"
          EXPECTED: "1.25.21"
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
          - name: Test weaviate-version-in-image action
            id: weaviate-version-in-image
            uses: ./.github/actions/weaviate-version-in-image
            with:
              image_tag: ${{ env.IMAGE_TAG }}
          - name: Verify that the retrieved version matches the expected one
            run: |
              echo "Expected: ${{ env.EXPECTED }}"
              echo "Actual: ${{ steps.weaviate-version-in-image.outputs.weaviate_version }}"
              if [ "${{ env.EXPECTED }}" != "${{ steps.weaviate-version-in-image.outputs.weaviate_version }}" ]; then
                echo "The retrieved version does not match the expected one."
                exit 1
              fi